### ISSUE TITLE
background 지원 타입 

### ISSUE THREAD

**Issue by okinawaa** [HoseungJang/scratchable#1]
안녕하세요!

현재 background type이 single, linear-gradient, image 세가지가 있는데, 혹시 lottie (json) background에 사용할 수 있는 방법이 있을까요?

**Comment by hoseungme** [comment]
안녕하세요, 오랜만이네요. 지금은 지원하지 않구요, Lottie에 canvas renderer가 있는 걸로 알고있는데, 확인해서 구현해보고 알려드릴게요.

**Comment by okinawaa** [comment]
감사합니다!! ㅎㅎ

**Comment by hoseungme** [comment]
구현해보았는데, lottie-web의 canvas renderer에 직접 접근해서 다루는 방법이 없는 것 같아서 일단은 close하고 더 알아볼게요.
